spring: 
 datasource: 
  url: jdbc:postgresql://localhost:5432/AcademiaBase?useTimezone=true&serverTimezone=U&useLegacyDate
  username: postgres
  password: aluno123
 jpa:
  show-sql: true 
  hibernate: 
   ddl-auto: update 
  properties: 
   hibernate.format_sql: true
